name: Publish Package to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"
          registry-url: "https://registry.npmjs.org"

      - name: Check version changes
        id: check
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          LATEST_TEG=$(git describe --tags --abbrev=0  2>/dev/null || echo "v0.0.0")
          # Remove 'v' prefix from the tag for version comparison
          echo "Latest tag: $LATEST_TEG"

          LATEST_VERSION=${LATEST_TEG#v}

          echo "Current version: $CURRENT_VERSION"
          echo "Latest tag version: $LATEST_VERSION"

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "Version changed from $LATEST_VERSION to $CURRENT_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          echo "Version not changed."
          fi

      - name: Install dependencies
        run: npm install

      - name: Rollup
        run: npm run rollup
        if: steps.check.outputs.version_changed == 'true'

      - name: Publish to NPM
        run: npm publish --access public --no-git-checks
        if: steps.check.outputs.version_changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Tag release
        if: steps.check.outputs.version_changed == 'true'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a "v${{ steps.check.outputs.new_version }}" -m "v${{ steps.check.outputs.new_version }}"
          git push origin "v${{ steps.check.outputs.new_version }}"
